# Generated by Django 5.0.4 on 2024-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
