# Generated by Django 5.0.4 on 2024-04-26 22:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
