# Generated by Django 5.0.4 on 2024-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='Bindu_Blood_Bank_Api/Users'),
        ),
    ]
