# Generated by Django 5.0.4 on 2024-05-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_donation_date',
        ),
    ]
