# Generated by Django 5.0.4 on 2024-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_last_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_donation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
