# Generated by Django 5.0.4 on 2024-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
