# Generated by Django 5.0.4 on 2024-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='Bindu_Blood_Bank_Api/Services'),
        ),
    ]
